

try {
    console.log(name)
} catch (error) {
    console.log("test")
}finally{
    console.log("finally block")
}





